### ISSUE TITLE
Tarea 3

### ISSUE THREAD

**Issue by MiguelMurua** [MiguelMurua/ProyectoIntegrador-ISPC#5]
Extraer del material de Scrum los siguientes conceptos : _ceremonias, artefactos y roles_.

**Comment by MiguelMurua** [comment]
Ya renombre el Readme.md a ConceptosScrum.md, ahora queda ir colocando los conceptos en cada apartado.

**Comment by Andresdesarrollo** [comment]
Bueno ,eso hay que hacer , si.

**Comment by MiguelMurua** [comment]
Si, hay que sacar los conceptos Scrum marcados en la issue y agregarlos al archivo ConceptosScrum.md que esta en el main del repositorio.. en el meet de las 22hs vamos a hablar de eso.. espero que puedan estar todos así nos organizamos.

**Comment by PatriciAleSolis** [comment]
hola Miguel, todavía estoy iniciando en github, por lo que lo único que te puedo decir, es que a penas logre conectarme desde la VSC, podre subir el CV

**Comment by Silvina-Dew** [comment]
hola Miguel. ya  he realizado mi branch del cv. Me falta un paso para subirlo a remoto.
