### ISSUE TITLE
Colaboración a ConceptosScrum.

### ISSUE THREAD

**Issue by MiguelMurua** [MiguelMurua/ProyectoIntegrador-ISPC#8]
Cada colaborador deberá hacer un aporte a los conceptos marcados en la Issue "Tarea 3",  modificar el archivo ConceptosScrum.md del main y guardarlo en la rama que le corresponda a cada uno.

**Comment by fede9087** [comment]
Actualice  mi rama agregando contenido a ConceptosScrum.md, luego hice merge al main
